<script type="text/javascript">
<!--
var pass_field = '<?=$pass_field;?>';
//-->
</script>
<div id="logindiv">
	<fieldset>
		<div id="anonymous_image">
			<?=$helper->img('anonymous','usuario'); ?>
		</div>
		<div id="login_response"><!-- spanner --></div>
		<div id='login_form'>
			<form action="<?php echo $helper->url('login/dologin')?>" method="post" id="form_login">
          		<table>
          			<tbody>
          				<tr>
          					<td><label for="login">Nombre de Usuario</label></td>
          					<td><input type="text" name="<?php echo $user_field?>" id="<?php echo $user_field?>" /></td>
          				</tr>
          				<tr>
          					<td><label for="psw">Password</label></td>
          					<td><input type="password" name="<?php echo $pass_field?>" id="<?php echo $pass_field?>" /></td>
          				</tr>
          				<tr>
          					<td align="center" colspan="2"><input type="submit" value="Ingresar" name="submit" id="submit" class='button' /></td>
          				</tr>
          			</tbody>
          		</table>
          	</form>
		</div>
		<div id="ajax_loading">
			<?=$helper->img('loading','cargando'); ?>
		</div>
	</fieldset>
</div>
